apiVersion: v1
kind: Service
metadata:
  name: load-balancer-frontend-e8
  namespace: grupo-08-prod
spec:
  selector:
    app: frontend-e8
  ports:
    - protocol: 'TCP'
      port: 3000
      targetPort: 3000
  type: LoadBalancer