apiVersion: v1
kind: Pod
metadata:
  name: frontend-e8
  labels:
    app: frontend-e8
spec:
  containers:
    - name: frontend-e8
      image: nettojulio/frontend-e8:stable
      ports:
        - containerPort: 3000